version: '3'

services:
  freepbx:
    image: scjtqs/asterisk-freepbx:latest
    container_name: freepbx
    ports:
      - "1283:80"
      - "1284:443"
      - "4569:4569/udp"
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "10000-10100:10000-10100/udp" #通话媒体端口，需要自行在freepbx后台设置范围。太多了docker映射不过来，劲量小吧。
    environment:
      - TZ=Asia/Shanghai
      - DBENGINE=mysql
      - DBNAME=asterisk
      - DBHOST=192.168.123.123  # mysql的部署就不多描述了
      - DBPORT=3306
      - CDRDBNAME=asteriskcdrdb
      - DBUSER=asterisk
      - DBPASS=asteriskPass123
      - USER=asterisk
      - GROUP=asterisk
      - WEBROOT=/var/www/html
      - ASTETCDIR=/etc/asterisk
      - ASTMODDIR=/usr/lib64/asterisk/modules
      - ASTVARLIBDIR=/var/lib/asterisk
      - ASTAGIDIR=/var/lib/asterisk/agi-bin
      - ASTSPOOLDIR=/var/spool/asterisk
      - ASTRUNDIR=/var/run/asterisk
      - AMPBIN=/var/lib/asterisk/bin
      - AMPSBIN=/usr/sbin
      - AMPCGIBIN=/var/www/cgi-bin
      - AMPPLAYBACK=/var/lib/asterisk/playback
      - FORWARD_URL=http://forwardsms:8080/api/v1/sms/receive #对应下面的转发服务
      - AT_PORT=/dev/ttyUSB2        # 第一次运行生成配置时有效。后面需要自行去./asterisk/etcasterisk/quectel.conf 下去手动修改
      - AUDIO_PORT=/dev/ttyUSB1     # 第一次运行生成配置时有效。后面需要自行去./asterisk/etcasterisk/quectel.conf 下去手动修改
      - FORWARD_SECRET=YourFowdaardSecret   # 短信推送通信秘钥，和下面服务的填一样。
      - PHONE_ID=SIM1_1861xxxxxxxxxx # 短信推送的时候标识字段。
      - SMTP_SERVER=smtp.mycompany.com:587 # 您的SMTP服务器地址和端口
      - SMTP_USERNAME=freepbx@mycompany.com # 您的邮箱账号
      - SMTP_PASSWORD=YourSecureAppPassword # 您的邮箱密码
      - SMTP_SSL=false   # 是否是走的ssl模式，比如465端口。.587是tls，不需要开这个。
      - ACME_DNS_TYPE=dns_cf  # acme.sh dns证书的验证方式。这里demo是cloudflare
      - ACME_ENABLE=true      # 是否需要通过acme的dns方式帮你生成一个https证书
      - ACME_EMAIL=abc@def.com # 用于acme.sh注册的邮箱
      # dns_cf需要的环境变量 demo。将你选择的ACME_DNS_TYPE需要的环境变量放下面。其他方式的方对应变量名称
      - CF_Token=124
      - CF_Account_ID=568
      - CF_Email=sip@mail.com
      - FQDN=sip.domain.com        # 需要生成证书的域名
    volumes:
      - ./data:/data              # 短信db、转发日志等
      - ./asterisk/varasterisk:/var/lib/asterisk  # asterisk的lib文件夹
      - ./asterisk/etcasterisk:/etc/asterisk      # asterisk的 /etc/asterisk的文件夹内容
      - ./asterisk/logs:/var/log/asterisk         # asterisk的日志
      - ./asterisk/wwwdata:/var/www/html          # freepbx的内容
      - ./asterisk/records:/var/spool/asterisk/monitor
    restart: always
    privileged: true                              # 开了它，融器才具备root权限，能读取到/dev/ttyUSBx的数据
  # 转发短信到其他平台 配置文件参考 https://github.com/scjtqs2/ForwardSMS/blob/master/data/config/forward.yaml
  forwardsms:
    image: ghcr.io/scjtqs2/forwardsms/forwardsms:latest
    container_name: forwardsms  # 命名方便freepbx调用
    environment:
      - DEBUG=0
      - FORWARD_SECRET=YourFowdaardSecret
      - HTTP_PORT=8080
      - TZ=Asia/Shanghai
    volumes:
      - ./forward.yaml:/data/config/forward.yaml
    restart: always
